spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//192.168.41.7:1521/xepdb1
    username: healthcare
    password: team1!
  servlet:
    multipart:
      location: c:\\Temp\\upload
      max-file-size: 500MB
      max-request-size: 500MB
  server:
    address: 192.168.41.204
    port: 8080

logging:
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
          EnumType: trace
        SQL: debug
