spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//:1521/xepdb1
    username: 
    password: 

logging:
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
          EnumType: trace
        SQL: debug
      